// +build !ignore_autogenerated

/*
Copyright 2021 The Alibaba Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/apps/v1"
	batchv1 "k8s.io/api/batch/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgorithmSetting) DeepCopyInto(out *AlgorithmSetting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgorithmSetting.
func (in *AlgorithmSetting) DeepCopy() *AlgorithmSetting {
	if in == nil {
		return nil
	}
	out := new(AlgorithmSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgorithmSpec) DeepCopyInto(out *AlgorithmSpec) {
	*out = *in
	if in.AlgorithmSettings != nil {
		in, out := &in.AlgorithmSettings, &out.AlgorithmSettings
		*out = make([]AlgorithmSetting, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgorithmSpec.
func (in *AlgorithmSpec) DeepCopy() *AlgorithmSpec {
	if in == nil {
		return nil
	}
	out := new(AlgorithmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeasibleSpace) DeepCopyInto(out *FeasibleSpace) {
	*out = *in
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeasibleSpace.
func (in *FeasibleSpace) DeepCopy() *FeasibleSpace {
	if in == nil {
		return nil
	}
	out := new(FeasibleSpace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metric) DeepCopyInto(out *Metric) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metric.
func (in *Metric) DeepCopy() *Metric {
	if in == nil {
		return nil
	}
	out := new(Metric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectiveSpec) DeepCopyInto(out *ObjectiveSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectiveSpec.
func (in *ObjectiveSpec) DeepCopy() *ObjectiveSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectiveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterAssignment) DeepCopyInto(out *ParameterAssignment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterAssignment.
func (in *ParameterAssignment) DeepCopy() *ParameterAssignment {
	if in == nil {
		return nil
	}
	out := new(ParameterAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterCategory) DeepCopyInto(out *ParameterCategory) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]ParameterSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterCategory.
func (in *ParameterCategory) DeepCopy() *ParameterCategory {
	if in == nil {
		return nil
	}
	out := new(ParameterCategory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterSpec) DeepCopyInto(out *ParameterSpec) {
	*out = *in
	in.FeasibleSpace.DeepCopyInto(&out.FeasibleSpace)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterSpec.
func (in *ParameterSpec) DeepCopy() *ParameterSpec {
	if in == nil {
		return nil
	}
	out := new(ParameterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilingCondition) DeepCopyInto(out *ProfilingCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilingCondition.
func (in *ProfilingCondition) DeepCopy() *ProfilingCondition {
	if in == nil {
		return nil
	}
	out := new(ProfilingCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilingExperiment) DeepCopyInto(out *ProfilingExperiment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilingExperiment.
func (in *ProfilingExperiment) DeepCopy() *ProfilingExperiment {
	if in == nil {
		return nil
	}
	out := new(ProfilingExperiment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProfilingExperiment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilingExperimentList) DeepCopyInto(out *ProfilingExperimentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProfilingExperiment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilingExperimentList.
func (in *ProfilingExperimentList) DeepCopy() *ProfilingExperimentList {
	if in == nil {
		return nil
	}
	out := new(ProfilingExperimentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProfilingExperimentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilingExperimentSpec) DeepCopyInto(out *ProfilingExperimentSpec) {
	*out = *in
	if in.TunableParameters != nil {
		in, out := &in.TunableParameters, &out.TunableParameters
		*out = make([]ParameterCategory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Objective = in.Objective
	in.Algorithm.DeepCopyInto(&out.Algorithm)
	if in.MaxNumTrials != nil {
		in, out := &in.MaxNumTrials, &out.MaxNumTrials
		*out = new(int32)
		**out = **in
	}
	if in.Parallelism != nil {
		in, out := &in.Parallelism, &out.Parallelism
		*out = new(int32)
		**out = **in
	}
	in.ClientTemplate.DeepCopyInto(&out.ClientTemplate)
	in.ServicePodTemplate.DeepCopyInto(&out.ServicePodTemplate)
	if in.ServiceProgressDeadline != nil {
		in, out := &in.ServiceProgressDeadline, &out.ServiceProgressDeadline
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilingExperimentSpec.
func (in *ProfilingExperimentSpec) DeepCopy() *ProfilingExperimentSpec {
	if in == nil {
		return nil
	}
	out := new(ProfilingExperimentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilingExperimentStatus) DeepCopyInto(out *ProfilingExperimentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ProfilingCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.CurrentOptimalTrial.DeepCopyInto(&out.CurrentOptimalTrial)
	if in.TrialResultList != nil {
		in, out := &in.TrialResultList, &out.TrialResultList
		*out = make([]TrialResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.RunningTrialList != nil {
		in, out := &in.RunningTrialList, &out.RunningTrialList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PendingTrialList != nil {
		in, out := &in.PendingTrialList, &out.PendingTrialList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailedTrialList != nil {
		in, out := &in.FailedTrialList, &out.FailedTrialList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SucceededTrialList != nil {
		in, out := &in.SucceededTrialList, &out.SucceededTrialList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KilledTrialList != nil {
		in, out := &in.KilledTrialList, &out.KilledTrialList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilingExperimentStatus.
func (in *ProfilingExperimentStatus) DeepCopy() *ProfilingExperimentStatus {
	if in == nil {
		return nil
	}
	out := new(ProfilingExperimentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Trial) DeepCopyInto(out *Trial) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Trial.
func (in *Trial) DeepCopy() *Trial {
	if in == nil {
		return nil
	}
	out := new(Trial)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Trial) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrialAssignment) DeepCopyInto(out *TrialAssignment) {
	*out = *in
	if in.ParameterAssignments != nil {
		in, out := &in.ParameterAssignments, &out.ParameterAssignments
		*out = make([]ParameterAssignment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrialAssignment.
func (in *TrialAssignment) DeepCopy() *TrialAssignment {
	if in == nil {
		return nil
	}
	out := new(TrialAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrialCondition) DeepCopyInto(out *TrialCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrialCondition.
func (in *TrialCondition) DeepCopy() *TrialCondition {
	if in == nil {
		return nil
	}
	out := new(TrialCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrialList) DeepCopyInto(out *TrialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Trial, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrialList.
func (in *TrialList) DeepCopy() *TrialList {
	if in == nil {
		return nil
	}
	out := new(TrialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrialResult) DeepCopyInto(out *TrialResult) {
	*out = *in
	if in.TunableParameters != nil {
		in, out := &in.TunableParameters, &out.TunableParameters
		*out = make([]ParameterAssignment, len(*in))
		copy(*out, *in)
	}
	if in.ObjectiveMetricsObserved != nil {
		in, out := &in.ObjectiveMetricsObserved, &out.ObjectiveMetricsObserved
		*out = make([]Metric, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrialResult.
func (in *TrialResult) DeepCopy() *TrialResult {
	if in == nil {
		return nil
	}
	out := new(TrialResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrialSpec) DeepCopyInto(out *TrialSpec) {
	*out = *in
	if in.SamplingResult != nil {
		in, out := &in.SamplingResult, &out.SamplingResult
		*out = make([]ParameterAssignment, len(*in))
		copy(*out, *in)
	}
	out.Objective = in.Objective
	in.ClientTemplate.DeepCopyInto(&out.ClientTemplate)
	in.ServicePodTemplate.DeepCopyInto(&out.ServicePodTemplate)
	if in.ServiceProgressDeadline != nil {
		in, out := &in.ServiceProgressDeadline, &out.ServiceProgressDeadline
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrialSpec.
func (in *TrialSpec) DeepCopy() *TrialSpec {
	if in == nil {
		return nil
	}
	out := new(TrialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrialStatus) DeepCopyInto(out *TrialStatus) {
	*out = *in
	if in.TrialResult != nil {
		in, out := &in.TrialResult, &out.TrialResult
		*out = new(TrialResult)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]TrialCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.ServiceDeployment != nil {
		in, out := &in.ServiceDeployment, &out.ServiceDeployment
		*out = new(v1.Deployment)
		(*in).DeepCopyInto(*out)
	}
	if in.StressTestJob != nil {
		in, out := &in.StressTestJob, &out.StressTestJob
		*out = new(batchv1.Job)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrialStatus.
func (in *TrialStatus) DeepCopy() *TrialStatus {
	if in == nil {
		return nil
	}
	out := new(TrialStatus)
	in.DeepCopyInto(out)
	return out
}
