# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="api.proto",
    package="api.storage",
    syntax="proto3",
    serialized_options=b"Z\022../grpc_storage/go",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\tapi.proto\x12\x0b\x61pi.storage"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t"\x11\n\x0fSaveResultReply"b\n\x11SaveResultRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x12\n\ntrial_name\x18\x02 \x01(\t\x12&\n\x07results\x18\x04 \x03(\x0b\x32\x15.api.storage.KeyValue"9\n\x10GetResultRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x12\n\ntrial_name\x18\x02 \x01(\t"_\n\x0eGetResultReply\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x12\n\ntrial_name\x18\x02 \x01(\t\x12&\n\x07results\x18\x04 \x03(\x0b\x32\x15.api.storage.KeyValue2\x99\x01\n\x02\x44\x42\x12J\n\nSaveResult\x12\x1e.api.storage.SaveResultRequest\x1a\x1c.api.storage.SaveResultReply\x12G\n\tGetResult\x12\x1d.api.storage.GetResultRequest\x1a\x1b.api.storage.GetResultReplyB\x14Z\x12../grpc_storage/gob\x06proto3',
)


_KEYVALUE = _descriptor.Descriptor(
    name="KeyValue",
    full_name="api.storage.KeyValue",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="api.storage.KeyValue.key",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="api.storage.KeyValue.value",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=26,
    serialized_end=64,
)


_SAVERESULTREPLY = _descriptor.Descriptor(
    name="SaveResultReply",
    full_name="api.storage.SaveResultReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=66,
    serialized_end=83,
)


_SAVERESULTREQUEST = _descriptor.Descriptor(
    name="SaveResultRequest",
    full_name="api.storage.SaveResultRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="namespace",
            full_name="api.storage.SaveResultRequest.namespace",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="trial_name",
            full_name="api.storage.SaveResultRequest.trial_name",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="results",
            full_name="api.storage.SaveResultRequest.results",
            index=2,
            number=4,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=85,
    serialized_end=183,
)


_GETRESULTREQUEST = _descriptor.Descriptor(
    name="GetResultRequest",
    full_name="api.storage.GetResultRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="namespace",
            full_name="api.storage.GetResultRequest.namespace",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="trial_name",
            full_name="api.storage.GetResultRequest.trial_name",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=185,
    serialized_end=242,
)


_GETRESULTREPLY = _descriptor.Descriptor(
    name="GetResultReply",
    full_name="api.storage.GetResultReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="namespace",
            full_name="api.storage.GetResultReply.namespace",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="trial_name",
            full_name="api.storage.GetResultReply.trial_name",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="results",
            full_name="api.storage.GetResultReply.results",
            index=2,
            number=4,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=244,
    serialized_end=339,
)

_SAVERESULTREQUEST.fields_by_name["results"].message_type = _KEYVALUE
_GETRESULTREPLY.fields_by_name["results"].message_type = _KEYVALUE
DESCRIPTOR.message_types_by_name["KeyValue"] = _KEYVALUE
DESCRIPTOR.message_types_by_name["SaveResultReply"] = _SAVERESULTREPLY
DESCRIPTOR.message_types_by_name["SaveResultRequest"] = _SAVERESULTREQUEST
DESCRIPTOR.message_types_by_name["GetResultRequest"] = _GETRESULTREQUEST
DESCRIPTOR.message_types_by_name["GetResultReply"] = _GETRESULTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyValue = _reflection.GeneratedProtocolMessageType(
    "KeyValue",
    (_message.Message,),
    {
        "DESCRIPTOR": _KEYVALUE,
        "__module__": "api_pb2"
        # @@protoc_insertion_point(class_scope:api.storage.KeyValue)
    },
)
_sym_db.RegisterMessage(KeyValue)

SaveResultReply = _reflection.GeneratedProtocolMessageType(
    "SaveResultReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _SAVERESULTREPLY,
        "__module__": "api_pb2"
        # @@protoc_insertion_point(class_scope:api.storage.SaveResultReply)
    },
)
_sym_db.RegisterMessage(SaveResultReply)

SaveResultRequest = _reflection.GeneratedProtocolMessageType(
    "SaveResultRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _SAVERESULTREQUEST,
        "__module__": "api_pb2"
        # @@protoc_insertion_point(class_scope:api.storage.SaveResultRequest)
    },
)
_sym_db.RegisterMessage(SaveResultRequest)

GetResultRequest = _reflection.GeneratedProtocolMessageType(
    "GetResultRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETRESULTREQUEST,
        "__module__": "api_pb2"
        # @@protoc_insertion_point(class_scope:api.storage.GetResultRequest)
    },
)
_sym_db.RegisterMessage(GetResultRequest)

GetResultReply = _reflection.GeneratedProtocolMessageType(
    "GetResultReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETRESULTREPLY,
        "__module__": "api_pb2"
        # @@protoc_insertion_point(class_scope:api.storage.GetResultReply)
    },
)
_sym_db.RegisterMessage(GetResultReply)


DESCRIPTOR._options = None

_DB = _descriptor.ServiceDescriptor(
    name="DB",
    full_name="api.storage.DB",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=342,
    serialized_end=495,
    methods=[
        _descriptor.MethodDescriptor(
            name="SaveResult",
            full_name="api.storage.DB.SaveResult",
            index=0,
            containing_service=None,
            input_type=_SAVERESULTREQUEST,
            output_type=_SAVERESULTREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="GetResult",
            full_name="api.storage.DB.GetResult",
            index=1,
            containing_service=None,
            input_type=_GETRESULTREQUEST,
            output_type=_GETRESULTREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_DB)

DESCRIPTOR.services_by_name["DB"] = _DB

# @@protoc_insertion_point(module_scope)
