# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import api_pb2 as api__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveResult = channel.unary_unary(
                '/api.storage.DB/SaveResult',
                request_serializer=api__pb2.SaveResultRequest.SerializeToString,
                response_deserializer=api__pb2.SaveResultReply.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/api.storage.DB/GetResult',
                request_serializer=api__pb2.GetResultRequest.SerializeToString,
                response_deserializer=api__pb2.GetResultReply.FromString,
                _registered_method=True)


class DBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveResult,
                    request_deserializer=api__pb2.SaveResultRequest.FromString,
                    response_serializer=api__pb2.SaveResultReply.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=api__pb2.GetResultRequest.FromString,
                    response_serializer=api__pb2.GetResultReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.storage.DB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.storage.DB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.storage.DB/SaveResult',
            api__pb2.SaveResultRequest.SerializeToString,
            api__pb2.SaveResultReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.storage.DB/GetResult',
            api__pb2.GetResultRequest.SerializeToString,
            api__pb2.GetResultReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
