# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x0b\x61pi.storage\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x11\n\x0fSaveResultReply\"b\n\x11SaveResultRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x12\n\ntrial_name\x18\x02 \x01(\t\x12&\n\x07results\x18\x04 \x03(\x0b\x32\x15.api.storage.KeyValue\"9\n\x10GetResultRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x12\n\ntrial_name\x18\x02 \x01(\t\"_\n\x0eGetResultReply\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x12\n\ntrial_name\x18\x02 \x01(\t\x12&\n\x07results\x18\x04 \x03(\x0b\x32\x15.api.storage.KeyValue2\x99\x01\n\x02\x44\x42\x12J\n\nSaveResult\x12\x1e.api.storage.SaveResultRequest\x1a\x1c.api.storage.SaveResultReply\x12G\n\tGetResult\x12\x1d.api.storage.GetResultRequest\x1a\x1b.api.storage.GetResultReplyB\x14Z\x12../grpc_storage/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022../grpc_storage/go'
  _globals['_KEYVALUE']._serialized_start=26
  _globals['_KEYVALUE']._serialized_end=64
  _globals['_SAVERESULTREPLY']._serialized_start=66
  _globals['_SAVERESULTREPLY']._serialized_end=83
  _globals['_SAVERESULTREQUEST']._serialized_start=85
  _globals['_SAVERESULTREQUEST']._serialized_end=183
  _globals['_GETRESULTREQUEST']._serialized_start=185
  _globals['_GETRESULTREQUEST']._serialized_end=242
  _globals['_GETRESULTREPLY']._serialized_start=244
  _globals['_GETRESULTREPLY']._serialized_end=339
  _globals['_DB']._serialized_start=342
  _globals['_DB']._serialized_end=495
# @@protoc_insertion_point(module_scope)
