# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import api_pb2 as api__pb2
import grpc


class DBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveResult = channel.unary_unary(
            "/api.storage.DB/SaveResult",
            request_serializer=api__pb2.SaveResultRequest.SerializeToString,
            response_deserializer=api__pb2.SaveResultReply.FromString,
        )
        self.GetResult = channel.unary_unary(
            "/api.storage.DB/GetResult",
            request_serializer=api__pb2.GetResultRequest.SerializeToString,
            response_deserializer=api__pb2.GetResultReply.FromString,
        )


class DBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DBServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SaveResult": grpc.unary_unary_rpc_method_handler(
            servicer.SaveResult,
            request_deserializer=api__pb2.SaveResultRequest.FromString,
            response_serializer=api__pb2.SaveResultReply.SerializeToString,
        ),
        "GetResult": grpc.unary_unary_rpc_method_handler(
            servicer.GetResult,
            request_deserializer=api__pb2.GetResultRequest.FromString,
            response_serializer=api__pb2.GetResultReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "api.storage.DB", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class DB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveResult(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.storage.DB/SaveResult",
            api__pb2.SaveResultRequest.SerializeToString,
            api__pb2.SaveResultReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetResult(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.storage.DB/GetResult",
            api__pb2.GetResultRequest.SerializeToString,
            api__pb2.GetResultReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
